DEFAULT: &common
  LOGGING: True
  LOG_DIRECTORY: logs
  LOG_FILE: 'status.log'
  SECRET_KEY: 'cf875e6a24f845e29a824b5de962981d'
  HOST: localhost
  PORT: 4000
  DEBUG: True
  #SERVER_NAME: localhost
  JSONIFY_PRETTYPRINT_REGULAR: true
  REDIS_URL: 'redis://localhost:6379'
  STATUS_JSON: 'web/static/json/status.json'
  TRAJECTORY_DIR: 'web/static/json/trajectories/'
  ERDDAP_URL: 'http://data.ioos.us/gliders/erddap/tabledap/allDatasets.json'
  DAC_API: 'http://data.ioos.us/gliders/providers/api/deployment'
  FILE_DIR: '/data/data_dir/'
  GLIDER_EMAIL:
    EMAIL_ACCOUNT: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    EMAIL_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    EMAIL_FOLDER: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    OUTPUT_DIRECTORY: 'navo/cache'

DEVELOPMENT: &development
  <<: *common

PRODUCTION: &production
  <<: *common
  DEBUG: False

